apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDKjCCAhKgAwIBAgIQMg9KcLka0CXpALABUxXPIDANBgkqhkiG9w0BAQsFADAv
    MS0wKwYDVQQDEyQ4ZWU1Mzc2Yy00NjY2LTQ2NGMtOWE4Ni00MmRmYjU3MGMxMWYw
    HhcNMjEwNzE5MTgyMjQyWhcNMjYwNzE4MTkyMjQyWjAvMS0wKwYDVQQDEyQ4ZWU1
    Mzc2Yy00NjY2LTQ2NGMtOWE4Ni00MmRmYjU3MGMxMWYwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQCSk/MKMcYU8ECbQ/hD8Fr3/reddLlsZXB7OoLo6Ksq
    YwDNHKlqJvQ0StCep5AxH2S9kIxL48mU0ezM2q41CFAyjfAWTNFauk1YPlMfWq8R
    kraQv7K8HbZaEXf8iZG44pMCuJx5dm4s+ig0tlvRb3As2CWnBeMLHmekMNP1RYIa
    aqYz5vMpfqNyH3b3Pdu6Eje3JkNMcEw07ZrtbqbJfw93NVpnV7Gpt6+YX2blpheY
    Yq2yucbE9LMMNP3nKAD0A2EUQFTtAc0SuE2kZqQUt8nNTvbvBkA02GczSHuJvxdF
    p67julOKyU8rInD3F8Y4WD3wIKhQXe4+B71WN0RD5kg/AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSzcxj2lXrrgoKx
    g91OAuuFu4mrIDANBgkqhkiG9w0BAQsFAAOCAQEAKvnlubUUnbnlmo1MoDqia3dq
    JC62FwEdH6LAgsFZVQkazBYmXhe4GCrjZYHbI/hc2CnFPPc1uQ3TKaQA6SFDstzF
    sZf+jwtMD+LCSrsIt7MX0+8FSzHt31zayg8Us/RPL2hOIvrDVzygqZpS3BJDQZDp
    R61vfneU2mdymK3ugsrCEwDYe2/kb5QZSvELnfcow0GNzxhxgPoIFEfOVwY5/JQ2
    GdCvYfP74LMd1JDGfVVTBnogs1NuKl7EUjj3gOF9G5ArUnHFpRlp31W9yZ4nt9Wk
    nVosQk0jBJaSqWfXn2Q5TQiLHOQP6ltNHJey6RFFHK/ImmdskT7K4Vq2tFgYSg==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: kube-root-ca.crt
